export { default as BookSection } from "./BookSection";
export { default as QuestionCategorySection } from "./QuestionCategorySection";
export { default as TestExamSection } from "./TestExamSection";
export { default as GoldExamSection } from "./GoldExamSection";
export { default as ServicesSection } from "./ServicesSection";
export { default as SimpleQuestion } from "./SimpleQuestion";
export { default as Faq } from "./Faq";
export { default as HomeSideBar } from "./HomeSideBar";
export { default as SingleService } from "./SingleService";
